version: '3.8'
services:
  api:
    container_name: apirust-users
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: apirust/users
    ports:
      - "8080:3000"
    volumes:
      - ".:/app"
    healthcheck:
      test: curl --fail http://localhost:3000/api/v1/healthy || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    restart: always
